In [5]:
import numpy as np

a = np.array([200,175,30])
print(a,a.shape)
a = a.reshape((1,1,3))
print(a,a.shape)
a = np.tile(a, [2,2,1])
print(a,a.shape)

[200 175  30] (3,)
[[[200 175  30]]] (1, 1, 3)
[[[200 175  30]
  [200 175  30]]

 [[200 175  30]
  [200 175  30]]] (2, 2, 3)


In [8]:
import numpy as np
a = np.array([[1,1],[2,2]])
print(a)
b = np.array([2,3])
print(b)
print(a*b)

[[1 1]
 [2 2]]
[2 3]
[[2 3]
 [4 6]]


In [6]:
import numpy as np
print(np.random.randint(256, size=(10, 3)))
print(np.random.rand(10))

[[ 55  42 251]
 [ 21  58 204]
 [ 65 176 226]
 [114  53 168]
 [174 158 131]
 [ 41 247 129]
 [ 16 166 109]
 [246  66 125]
 [ 47 212 248]
 [252 181   7]]
[0.19067647 0.68388268 0.53469046 0.35033081 0.20653309 0.5624894
 0.1343749  0.85971887 0.46956145 0.48558901]


In [7]:
import numpy as np
np.max([1,2,3])

3