In [6]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [7]:
x = tf.random.normal([2,4])
w = tf.ones([4,3])
b = tf.zeros([3])
o = x@w+b
print(o)

tf.Tensor(
[[-0.72839797 -0.72839797 -0.72839797]
 [-3.8464518  -3.8464518  -3.8464518 ]], shape=(2, 3), dtype=float32)


In [10]:
fc = layers.Dense(3) # 定义全连接层的输出节点为 3
fc.build(input_shape=(2,4)) # 定义全连接层的输入节点为 4
fc.kernel

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.06502324,  0.5611595 , -0.36720055],
       [ 0.2966857 , -0.73969936,  0.15620637],
       [ 0.40362704, -0.1398651 , -0.03461528],
       [ 0.89309144,  0.4378445 ,  0.8108226 ]], dtype=float32)>

In [15]:
y_true = tf.constant([1.,2.,3.,4.])
y_pred = tf.constant([3.,4.,2.,5.])
print(keras.losses.mse(y_true, y_pred))

tf.Tensor(2.5, shape=(), dtype=float32)


In [22]:
x = tf.random.normal([4,28*28])
fc = layers.Dense(512, activation=tf.nn.relu)
h1 = fc(x)
print(h1)
#fc.kernel
#fc.bias
fc.trainable_variables

tf.Tensor(
[[0.12107342 1.3612459  1.0710683  ... 0.         1.3269179  0.        ]
 [0.2883655  0.         0.         ... 1.4859645  0.3728098  0.        ]
 [0.         0.24666283 0.47269028 ... 0.         0.2391634  0.        ]
 [0.         0.         0.8222501  ... 0.9916607  0.9383684  0.        ]], shape=(4, 512), dtype=float32)


[<tf.Variable 'dense_8/kernel:0' shape=(784, 512) dtype=float32, numpy=
 array([[ 0.06505223, -0.05795492, -0.03532369, ..., -0.02306877,
         -0.00564887,  0.0248144 ],
        [-0.04159698,  0.05464664, -0.01047857, ..., -0.04402865,
         -0.02748585, -0.01634828],
        [-0.02462201,  0.02261797,  0.00078795, ..., -0.04948078,
         -0.04163136, -0.00418607],
        ...,
        [-0.05944968,  0.02444524,  0.0016683 , ..., -0.04175289,
          0.02096687,  0.0194212 ],
        [-0.03133974,  0.05583162, -0.00167322, ..., -0.00290053,
         -0.05900272, -0.06180567],
        [-0.01633928,  0.0233305 ,  0.05633084, ...,  0.05788925,
          0.05331792,  0.06532206]], dtype=float32)>,
 <tf.Variable 'dense_8/bias:0' shape=(512,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,