In [6]:
import tensorflow as tf

# 随机从均匀分布上产生一个tensor
with tf.Session() as sess:
    print(sess.run(tf.random_uniform([1], -1.0, 1.0, dtype=tf.float32)))

[0.17968822]


In [11]:
import tensorflow as tf

# 产生一个[2,2]的全零tensor
biases = tf.Variable(tf.zeros([2,2]))
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(biases))

[[0. 0.]
 [0. 0.]]


In [26]:
import tensorflow as tf

x = [[1,2,3],
    [1,2,3],
    [1,2,3]]
x = tf.cast(x, tf.float32)
y = [[2,3,4],
     [2,3,4],
     [2,3,4]]
y = tf.cast(y, tf.float32)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tf.multiply(x,y)))

[[ 2.  6. 12.]
 [ 2.  6. 12.]
 [ 2.  6. 12.]]


In [16]:
import tensorflow as tf
import numpy as np

x = [[1,2,3],
      [1,2,3]]
print(x)
print(np.transpose(x))
xx = tf.cast(x,tf.float32)

mean_all = tf.reduce_mean(xx, keep_dims=False)
mean_0 = tf.reduce_mean(xx, axis=0, keep_dims=False)
mean_1 = tf.reduce_mean(xx, axis=1, keep_dims=False)

with tf.Session() as sess:
    m_a,m_0,m_1 = sess.run([mean_all, mean_0, mean_1])
 
print(m_a)    # output: 2.0
print(m_0)    # output: [ 1.  2.  3.]
print(m_1)    # output:  [ 2.  2.]

[[1, 2, 3], [1, 2, 3]]
[[1 1]
 [2 2]
 [3 3]]
2.0
[1. 2. 3.]
[2. 2.]


In [20]:
import tensorflow as tf
import numpy as np

# 求解线性规划问题

# create data
x_data = np.random.rand(100).astype(np.float32)
y_data = x_data*0.1 + 0.3

# create tensorflow structure
Weights = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
biases = tf.Variable(tf.zeros([1]))

y = Weights*x_data + biases
loss = tf.reduce_mean(tf.square(y-y_data))

optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss)

# 
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)          # Very important

for step in range(301):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(Weights), sess.run(biases))

0 [-0.42196473] [0.8057858]
20 [-0.07911876] [0.39596522]
40 [0.04792479] [0.3279]
60 [0.08486017] [0.30811137]
80 [0.09559841] [0.30235824]
100 [0.09872033] [0.3006856]
120 [0.09962797] [0.30019933]
140 [0.09989185] [0.30005795]
160 [0.09996856] [0.30001685]
180 [0.09999086] [0.3000049]
200 [0.09999735] [0.30000144]
220 [0.09999923] [0.30000043]
240 [0.09999978] [0.30000013]
260 [0.0999999] [0.30000007]
280 [0.0999999] [0.30000007]
300 [0.0999999] [0.30000007]


In [4]:
# tf.gradients的作用
import tensorflow as tf

# with tf.variable_scope('test_gradients'):
with tf.variable_scope('test_gradients', reuse=True):
    w1 = tf.get_variable('w1', shape=[3])
    w2 = tf.get_variable('w2', shape=[3])
    w3 = tf.get_variable('w3', shape=[3])
    w4 = tf.get_variable('w4', shape=[3])

    z1 = 3 * w1 + 2 * w2+ w3
    z2 = -1 * w3 + w4

    grads1 = tf.gradients([z1, z2], [w1, w2, w3, w4])
    grads2 = tf.gradients([z1, z2], [w1, w2, w3, w4], grad_ys=[[-2.0, -3.0, -4.0], [-5.0, -5.0, -6.0]])

    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        g1, g2 = sess.run([grads1,grads2])
        print('grads1:', g1)
        print('grads2:', g2)

grads1: [array([3., 3., 3.], dtype=float32), array([2., 2., 2.], dtype=float32), array([0., 0., 0.], dtype=float32), array([1., 1., 1.], dtype=float32)]
grads2: [array([ -6.,  -9., -12.], dtype=float32), array([-4., -6., -8.], dtype=float32), array([3., 2., 2.], dtype=float32), array([-5., -5., -6.], dtype=float32)]
